### ISSUE TITLE
Provide web assembly mod

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_ast#120]
Could a web assembly mod be provided like [deno_doc](https://github.com/denoland/deno_doc/issues#usage-from-deno-cli-or-deploy) does?
This would be really useful for tools in [deno_std](https://github.com/denoland/deno_std).

Ref: https://github.com/denoland/deno_std/pull/2820#issuecomment-1295212385

**Comment by dsherret** [comment]
This would probably be hard to maintain and slow. I'd recommend instead sending the string to Wasm, then parsing with this crate there, doing the analysis, then returning the result back to javascript. That's what I do in [dnt](https://github.com/denoland/dnt).
