### ISSUE TITLE
missing crate feature "minifier"

### ISSUE THREAD

**Issue by deckchairlabs** [denoland/deno_ast#129]
`lib.rs` has a cfg annotation for the "minifier" feature, although the Cargo.toml doesn't specifiy it

**Comment by dsherret** [comment]
Oh, thanks for pointing it out. Probably leftover from when we removed the feature from this crate. We should remove that line in lib.rs. We don’t use a minifier and if someone wants to use swc’s then they can import that crate.

**Comment by deckchairlabs** [comment]
Not a problem, just found it confusing!
