### ISSUE TITLE
Map file extension to content type

### ISSUE THREAD

**Issue by Cre3per** [denoland/deno_ast#133]
https://github.com/denoland/deno/pull/17172 adds `--ext` to deno, eg.

```
deno run --ext js mod
```

`--ext` needs to map file extensions to mime types

The [mapping function](https://github.com/denoland/deno/pull/17172/files#diff-747e5bf0658bef1ca03cfa6b83c21b7ffc899ce4324557b2cc94356681e76699R515-R527) in deno is incomplete and temporary.

deno_ast's `MediaType` already maps module specifiers and mime types to `MediaType`. I think this is a good place to map

- file extensions to `MediaType`
- `MediaType` to mime types

**Comment by Cre3per** [comment]
I'd like to work on this.

There is no 1:1 mapping between file extensions and mime types, eg. `application/typescript` and `text/typescript` both have a ".ts" file extension. For a start, I'll write a mapping function based on the mime types in `from_content_type()`

**Comment by dsherret** [comment]
Sounds good to me!
