### ISSUE TITLE
Update swc_ecmascript

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno_ast#37]
https://github.com/denoland/deno/issues/10861 and https://github.com/denoland/deno/issues/12532 have been fixed by https://github.com/swc-project/swc/pull/2530, but `swc_ecmascript` hasn't been updated in a while.

cc @dsherret

**Comment by kitsonk** [comment]
See: https://github.com/denoland/deno/issues/12565#issuecomment-972371955

**Comment by dsherret** [comment]
Not sure how to fix this one...

```
Building deno...
    Updating crates.io index
error: failed to select a version for `indexmap`.
    ... required by package `swc_fast_graph v0.1.0`
    ... which satisfies dependency `swc_fast_graph = "^0.1"` of package `swc_bundler v0.82.0`
    ... which satisfies dependency `swc_bundler = "^0.82.0"` of package `deno_ast v0.6.0 (V:\deno_ast)`
    ... which satisfies path dependency `deno_ast` of package `deno v1.16.2 (V:\deno\cli)`
versions that meet the requirements `^1.7.0` are: 1.7.0

all possible versions conflict with previously selected packages.

  previously selected package `indexmap v1.6.2`
    ... which satisfies dependency `indexmap = "=1.6.2"` of package `deno_core v0.108.0 (V:\deno\core)`
    ... which satisfies path dependency `deno_core` of package `deno v1.16.2 (V:\deno\cli)`

failed to select a version for `indexmap` which could resolve this conflict
```

https://github.com/denoland/deno/blob/c82ce7413366c49ae44128797f91fe44113c5e8c/core/Cargo.toml#L18-L19
https://github.com/swc-project/swc/blob/51bee9bfd33b555c725105dddc23704e5a2245ed/crates/swc_fast_graph/Cargo.toml#L15
https://github.com/tkaitchuck/aHash/issues/95

**Comment by dsherret** [comment]
It seems we can just upgrade to 1.7.0. Everything seems to work when I try that. We'll just have to update the import_map crate.

**Comment by dsherret** [comment]
Somewhat blocked on https://github.com/swc-project/swc/discussions/2801

**Comment by dsherret** [comment]
Opened https://github.com/swc-project/swc/issues/2808
