### ISSUE TITLE
Compare cjs exports implementation with one in esm.sh

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_ast#75]
https://github.com/esm-dev/esm.sh/blob/master/packages/cjs-esm-exports/src/cjs.rs

We should at the minimum add more tests from here: https://github.com/esm-dev/esm.sh/blob/master/packages/cjs-esm-exports/src/test.rs

**Comment by LeoDog896** [comment]
The link changed, by the way: 
- https://github.com/ije/esm.sh/blob/main/packages/esm-cjs-lexer/src/cjs.rs
- https://github.com/ije/esm.sh/blob/main/packages/esm-cjs-lexer/src/test.rs
