### ISSUE TITLE
Add option to apply swc `ts_resolver` on parse

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_ast#8]
We should move in this code from deno_lint to this crate so it can be used in the deno lsp. I'm not sure exactly what that entails...

https://github.com/denoland/deno_lint/blob/7825cb95115bfdffc62c076c8f458b3424f7190c/src/ast_parser.rs#L114

Once this is done, we should open up a PR in deno to reuse the ast for linting.

**Comment by bartlomieju** [comment]
We need to double check if this change won't have impact on other tools. CC @kdy1 can you advise?

**Comment by kdy1** [comment]
It will not affect other tools if they don't use span hygiene to distinguish identifiers.
I don't expect applying `ts_resolver` twice to break code, because it ignores identifiers with a non-empty syntax context.
